Spacewar: Update from NothingOS 2.0.2 Hotfix build
- Pin NothingOS 1.5.6 HotwordEnrollment blobs, as the 2.0.2 ones seem to require some kind of NothingOS-specific resources
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nothing/NtFeaturesUtils;
- Update rootdir chowns
- Uppercase the device name again
- Update camera sepolicies

Co-authored-by: aswin7469 <aswinas@pixysos.com>
Change-Id: I96d837889cdbd4cd9652a7f5d5e716c3767c8aca