Spacewar: Pin hotword enrollment libs from NOS 1.5
The NothingOS 2.0.2 ones seem to require some kind of NothingOS-specific resources:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nothing/NtFeaturesUtils;

Change-Id: I811c3baba28bedbfcf0a79be540f1c4e9b264db6
Signed-off-by: x0x00044 <zlewchan@outlook.com>